### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by omnigenous** [dhth/omm#2]
https://aur.archlinux.org/

**Comment by CyberDudeJ** [comment]
Honestly I'd kill for an AUR package of this

**Comment by dhth** [comment]
While I work on publishing an AUR package for omm, would getting linux binaries directly from a [release](https://github.com/dhth/omm/releases) suffice for now? Something like this:

```bash
# choose a gzipped tarball based on your architecture
curl -s -L -o omm.tar.gz https://github.com/dhth/omm/releases/download/v0.2.1/omm_0.2.1_linux_amd64.tar.gz
tar -xvzf omm.tar.gz
# move omm to a location on your $PATH
omm
```

**Comment by dimatematik** [comment]
I've published [one](https://aur.archlinux.org/packages/omm) and ready to maintain it

Could you please provide instructions on how to verify tarball signatures? I see that cosign is used, but the public key (cosign.pub) is in .gitignore

**Comment by dhth** [comment]
@dimatematik Thanks a lot for publishing it :)

I've added `cosign.pub` to the [release assets](https://github.com/dhth/omm/releases/tag/v0.4.1). The tarballs (or any other files in the release, eg. checksum files) can be verified using:

```bash
cosign verify-blob --key cosign.pub --signature omm_0.4.1_linux_amd64.tar.gz.sig omm_0.4.1_linux_amd64.tar.gz
```

Since I am new to AUR packages, I have a question:
The AUR package lists `go` as a dependency. Since I'm already publishing linux binaries, would it be easier to point the source directly to a precompiled binary (eg. the way it's done [here](https://aur.archlinux.org/packages/goreleaser-pro-bin)), and remove the dependency?

**Comment by omnigenous** [comment]
> The AUR package lists go as a dependency. Since I'm already publishing linux binaries, would it be easier to point the source directly to a precompiled binary (eg. the way it's done [here](https://aur.archlinux.org/packages/goreleaser-pro-bin)), and remove the dependency?

I'm no expert either but I think that how it works:
- `package`: Latest version
- `package-git`: Latest git commit
- `package-bin`: Latest version binary

**Comment by dimatematik** [comment]
Thanks for clarifying the verification process!

The use of -bin packages is a matter of debate ([discussion example](https://www.reddit.com/r/archlinux/comments/u6bsbg/aur_to_bin_or_not_to_bin/)). Since the AUR is completely untrusted (maintainer == anyone), end users should verify that the binary was compiled by the original author of the code. As a maintainer, I am advised to validate the binary (as stated in the Arch package guidelines), but the end user cannot be sure of my honesty. The only way to verify whether a binary was provided by the code's author is through cryptographic verification. Currently makepkg natively only supports PGP keys, so checking with cosign will require the "cosign" dependency.
Personally, I don't think there is a problem with the "go" dependency. The AUR is designed to store build instructions. -bin packages are typically used for heavy projects (like browsers) and proprietary software.

**Comment by dhth** [comment]
@dimatematik Makes sense. A non bin package with dependencies sounds good, then.

Side note: I added more details on verifying the authenticity of release assets [here](https://github.com/dhth/omm#-verifying-release-artifacts).

**Comment by dimatematik** [comment]
Well, someone published the [-bin](https://aur.archlinux.org/packages/omm-bin) package) I think the issue can be marked as resolved
