### ISSUE TITLE
Windows release

### ISSUE THREAD

**Issue by graphixillusion** [dhth/omm#3]
Is Windows build planned?

**Comment by dhth** [comment]
Hi.
No, at-least not in the immediate future.  I do not have a Windows machine lying around, and without it I cannot verify that all features of omm will work properly there.

You can always install this on Windows via the go toolchain (`go install github.com/dhth/omm@v0.2.0`), and give it a shot.

**Comment by graphixillusion** [comment]
Actually it seems to work and no errors found so far. Just one question: where the created tasks are stored on the filesystem? I saw that during editing it uses the %temp% folder.

**Comment by dhth** [comment]
That's good to hear. Just out of curiosity, what text editor are you using to add/update task context?

Yeah, the db file path is defaulting to `.local/share` (a remnant from linux). The Windows counterpart for this is `AppData\Local` but since Windows support wasn't intended, I never programmed it in.

I just pushed a quick fix for this. Do you mind installing version `v0.2.1` of omm? If you already have a bunch of tasks accumulated in omm, you can just copy the old db file to `%USERNAME%\AppData\local\omm\omm.db` and omm should just pick it up. I will still wait to get hold of a Windows machine before I start publishing Windows binaries, but this should at least get omm using the right conventions on Windows. Thanks.

**Comment by graphixillusion** [comment]
I confirm: in version 0.2.1 the new path is `%LOCALAPPDATA%\omm\omm.db`

About the editor i didn't change anything so as i have vim installed, omm uses it for editing.

**Comment by dhth** [comment]
Thanks a lot!

Gotcha.

I'll add support for providing configuration via a yml/toml file soon 👍

**Comment by dhth** [comment]
JFYI, config support via a TOML file was added in [v0.3.0](https://github.com/dhth/omm/releases/tag/v0.3.0).

**Comment by plutonium-239** [comment]
Please just provide a package, compiling this took ~3-4 mins and maxed out the CPU, bad experience. 
If there are any bugs we'll be sure to let you know.

**Comment by dhth** [comment]
> Please just provide a build, compiling this took ~3-4 mins and maxed out the CPU, bad experience. If there are any bugs we'll be sure to let you know.

I am considering it, and collecting feedback for this [here](https://github.com/dhth/omm/discussions/51).
